name: "CI"
on:
  push:
    branches: master

permissions:
  pull_request: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./
          with:
            base: master
            head: master
            auto_merge: false
            retries: 0
